version: '3'

services:
  db:
    image: mysql:latest
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "F1Quiz"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      command:
            --sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION
    ports:
      - "3306:3306"
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
      - dbdata:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - db
    environment:
      UPLOAD_LIMIT: 1G
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      restart: always
    ports:
      - 8081:80
volumes:
  dbdata:
